export const rooms = [
  {
    id: 'r1',
    name: 'Cama Doble',
    establishment: 'Hostal Luna Iquitos',
    price: 120,
    image: '/room.png',
    desc: 'Habitación estándar con cama doble.',
    capacity: 2,
    amenities: ["Wifi", "Tv Smart 43\"", "Aire acondicionado", "Baño privado"]
  },
  {
    id: 'r2',
    name: 'Cama Triple',
    establishment: 'Hostal Luna Iquitos',
    price: 150,
    image: '/room.png',
    desc: 'Habitación para tres personas con distribución de camas según imagen.',
    capacity: 3,
    amenities: ["Wifi", "Tv Smart 43\"", "Aire acondicionado", "Baño privado"]
  },
  {
    id: 'r3',
    name: 'Habitación Decorada',
    establishment: 'Hostal Luna Iquitos',
    price: 190,
    image: '/room.png',
    desc: 'Habitación matrimonial con decoración romántica con pétalos de rosa y bebidas incluidas.',
    capacity: 2,
    amenities: ["Wifi", "Tv Smart 43\"", "Aire acondicionado", "Baño privado"]
  },
  {
    id: 'r4',
    name: 'Habitación Matrimonial Cama 2 Plazas',
    establishment: 'Raphaela Hostal',
    price: 0,
    image: '/room.png',
    desc: 'Habitación matrimonial estándar de 2 plazas.',
    capacity: 2,
    amenities: ["Wifi", "Netflix"],
    attributes: ["Confort", "Comodidad", "Privacidad", "Higiene"]
  },
  {
    id: 'r5',
    name: 'Habitación Matrimonial QUEEN',
    establishment: 'Raphaela Hostal',
    price: 0,
    image: '/room.png',
    desc: 'Habitación matrimonial amplia con cama tamaño Queen.',
    capacity: 2,
    amenities: ["Wifi", "Netflix"],
    attributes: ["Confort", "Comodidad", "Privacidad", "Higiene"]
  }
];

export const menu = [
  { id: 'm1', name: 'Tacacho con Cecina', category: 'Comidas', price: 35, image: '/tacacho.png', desc: 'Bolas de plátano asado con carne de cerdo ahumada.' },
  { id: 'm2', name: 'Tradicional Juane', category: 'Comidas', price: 28, image: '/juane.png', desc: 'Arroz, pollo, huevo envuelto en hoja de bijao.' },
  { id: 'm3', name: 'Patarashca', category: 'Comidas', price: 32, image: '/juane.png', desc: 'Pescado asado en hoja de bijao con ricas especias.' },
  { id: 'm4', name: 'Ensalada de Chonta', category: 'Comidas', price: 20, image: '/tacacho.png', desc: 'Refrescante ensalada de palmito fresco.' },
  { id: 'm5', name: 'INKA COLA', category: 'Bebidas', price: 3, image: '/camucamu.png', desc: '' },
  { id: 'm6', name: 'AGUA SIN GAS - CON GAS', category: 'Bebidas', price: 4, image: '/camucamu.png', desc: '' },
  { id: 'm7', name: 'SPORADE - POWERADE', category: 'Bebidas', price: 4, image: '/camucamu.png', desc: '' },
  { id: 'm8', name: 'VOLT', category: 'Bebidas', price: 0, image: '/camucamu.png', desc: '' },
  { id: 'm9', name: 'JARRA DE REFRESCO', category: 'Bebidas', price: 16, image: '/camucamu.png', desc: '' },
  { id: 'm10', name: 'CERVEZA CRISTAL 850 ML', category: 'Bebidas', price: 0, image: '/camucamu.png', desc: '' },
  { id: 'm11', name: 'CORONA - HEINEKEN - STELLA ARTOIS', category: 'Bebidas', price: 10, image: '/camucamu.png', desc: '' },
  { id: 'm12', name: 'RED BULL', category: 'Bebidas', price: 10, image: '/camucamu.png', desc: '' },
  { id: 'm13', name: 'CUSQUEÑA 620 ML', category: 'Bebidas', price: 12, image: '/camucamu.png', desc: '' },
  { id: 'm14', name: 'CUSQUEÑA 310 ML', category: 'Bebidas', price: 7, image: '/camucamu.png', desc: '' },
  { id: 'm15', name: 'CHILCANO CLÁSICO', category: 'A Base de Pisco', price: 15, image: '/camucamu.png', desc: '' },
  { id: 'm16', name: 'CHILCANO DE MARACUYÁ', category: 'A Base de Pisco', price: 15, image: '/camucamu.png', desc: '' },
  { id: 'm17', name: 'CHILCANO DE CAMU CAMU', category: 'A Base de Pisco', price: 15, image: '/camucamu.png', desc: '' },
  { id: 'm18', name: 'PISCO SOUR CLÁSICO', category: 'A Base de Pisco', price: 15, image: '/camucamu.png', desc: '' },
  { id: 'm19', name: 'MARACUYÁ SOUR', category: 'A Base de Pisco', price: 15, image: '/camucamu.png', desc: '' },
  { id: 'm20', name: 'CAMU CAMU SOUR', category: 'A Base de Pisco', price: 15, image: '/camucamu.png', desc: '' },
  { id: 'm21', name: 'ALGARROBINA', category: 'A Base de Pisco', price: 15, image: '/camucamu.png', desc: '' },
  { id: 'm22', name: 'MACHU PICCHU', category: 'A Base de Pisco', price: 15, image: '/camucamu.png', desc: '' },
  { id: 'm23', name: 'SACSAYHUAMAN', category: 'A Base de Pisco', price: 15, image: '/camucamu.png', desc: '' },
  { id: 'm24', name: 'MOJITO CLÁSICO', category: 'A Base de Ron', price: 15, image: '/camucamu.png', desc: '' },
  { id: 'm25', name: 'MOJITO DE COCO', category: 'A Base de Ron', price: 15, image: '/camucamu.png', desc: '' },
  { id: 'm26', name: 'DAIKIRI DE DURAZNO', category: 'A Base de Ron', price: 15, image: '/camucamu.png', desc: '' },
  { id: 'm27', name: 'DAIKIRI DE FRESA', category: 'A Base de Ron', price: 15, image: '/camucamu.png', desc: '' },
  { id: 'm28', name: 'CUBA LIBRE', category: 'A Base de Ron', price: 15, image: '/camucamu.png', desc: '' },
  { id: 'm29', name: 'CHAPITO', category: 'A Base de Ron', price: 15, image: '/camucamu.png', desc: '' },
  { id: 'm30', name: 'PIÑA COLADA', category: 'A Base de Ron', price: 15, image: '/camucamu.png', desc: '' },
  { id: 'm31', name: 'PANTERA ROSA', category: 'A Base de Ron', price: 15, image: '/camucamu.png', desc: '' },
  { id: 'm32', name: 'VASO DE RON (Capitan Morgan)', category: 'A Base de Ron', price: 18, image: '/camucamu.png', desc: '' },
  { id: 'm33', name: 'VASO DE RON (Etiqueta Negra)', category: 'A Base de Ron', price: 25, image: '/camucamu.png', desc: '' },
  { id: 'm34', name: 'TEQUILA SUNRISE', category: 'A Base de Tequila', price: 15, image: '/camucamu.png', desc: '' },
  { id: 'm35', name: 'MARGARITA CLÁSICA', category: 'A Base de Tequila', price: 15, image: '/camucamu.png', desc: '' },
  { id: 'm36', name: 'MARGARITA BLUE', category: 'A Base de Tequila', price: 15, image: '/camucamu.png', desc: '' },
  { id: 'm37', name: 'MICHELADA MEXICANA', category: 'A Base de Tequila', price: 15, image: '/camucamu.png', desc: '' },
  { id: 'm38', name: 'CAMU CAMU FROZEN', category: 'Frozen y Limonadas', price: 25, image: '/camucamu.png', desc: '' },
  { id: 'm39', name: 'MARACUYÁ FROZEN', category: 'Frozen y Limonadas', price: 25, image: '/camucamu.png', desc: '' },
  { id: 'm40', name: 'LIMONADA FROZEN', category: 'Frozen y Limonadas', price: 25, image: '/camucamu.png', desc: '' },
  { id: 'm41', name: 'CHICHA FROZEN', category: 'Frozen y Limonadas', price: 25, image: '/camucamu.png', desc: '' },
  { id: 'm42', name: 'LIMONADA (Hierba Buena o Acerezada)', category: 'Frozen y Limonadas', price: 25, image: '/camucamu.png', desc: '' },
  { id: 'm43', name: 'COMBO MORGAN - CHAPITO', category: 'Combos', price: 120, image: '/camucamu.png', desc: '3 Coca Colas de 500 ml + 1 Jugo de Naranja + 1 Bolsa de Hielo + 1 Capitan Morgan' },
  { id: 'm44', name: 'COMBO ETIQUETA ROJA', category: 'Combos', price: 120, image: '/camucamu.png', desc: '2 Agua Mineral con gas + 1 red bull + 1 Jonny Walker etiqueta roja' },
  { id: 'm45', name: 'COMBO CHIVAS', category: 'Combos', price: 180, image: '/camucamu.png', desc: '2 Agua Mineral con gas + 1 red bull + 1 Bolsa de Hielo + 1 Whiskey Chivas Regal' },
  { id: 'm46', name: 'CHIVAS JONNY WALKER BLACK', category: 'Combos', price: 220, image: '/camucamu.png', desc: '2 Agua Mineral con gas + 1 red bull + 1 Jonny Walker etiqueta negra' },
  { id: 'm47', name: 'TABERNERO BORGOÑA SEMI SECO - BOTELLA', category: 'Vinos', price: 45, image: '/camucamu.png', desc: '' },
  { id: 'm48', name: 'COPA DE VINO', category: 'Vinos', price: 10, image: '/camucamu.png', desc: '' },
  { id: 'm49', name: 'CASILLERO DEL DIABLO - BOTELLA', category: 'Vinos', price: 75, image: '/camucamu.png', desc: '' },
];

export const categories = ['Comidas', 'Bebidas', 'A Base de Pisco', 'A Base de Ron', 'A Base de Tequila', 'Frozen y Limonadas', 'Combos', 'Vinos'];
